# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Shape of Card Games
email: goadrich@hendrix.edu
description: >- 
 Welcome! For the past four years, I’ve been working with some amazing students to 
 build a card game simulation engine called CardStock, along with a new language 
 for programming card games named RECYCLE. This blog is a culmination and 
 continuation of this research project investigating the structure, dynamics, 
 and mechanics of card games.
baseurl: "/cardstock" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mgoadric
github_username:  mgoadric
show_excerpts: true
highlighter: rouge
collections:
  category:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
      
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
