---
title: The Shape of Card Games
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: category
  values:
    layout: category
email: goadrich@hendrix.edu
description: Welcome! For the past four years, I’ve been working with some amazing
  students to  build a card game simulation engine called CardStock, along with a
  new language  for programming card games named RECYCLE. This blog is a culmination
  and  continuation of this research project investigating the structure, dynamics,  and
  mechanics of card games.
baseurl: "/cardstock"
url: ''
twitter_username: mgoadric
github_username: mgoadric
show_excerpts: true
highlighter: rouge
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
